
# This file was *autogenerated* from the file saveTest.sage
from sage.all_cmdline import *   # import sage library

_sage_const_100 = Integer(100); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
from pathlib import Path

import numpy as np
import os




def write_file(fname, a):
    p = Path(fname)
    test_file = p.open('ab')
    np.save(test_file, a)
    test_file.close()

def load_file(fname):
    p = Path(fname)
    out_list = []
    with p.open('rb') as f:
        fsz = os.fstat(f.fileno()).st_size
        out = np.load(f)
        out_list.append(out)
        while f.tell() < fsz:
            out_list.append(np.load(f))
    return out_list

triang = load_file('triang.npy')
power = load_file('power.npy')

print('Number of triang: ',len(triang)) #6558
print('Number of power: ', len(power))

data_file = open('lift_1_40.txt', 'r')
data_x = []
for line in data_file:
    data = eval(line)
    if data[_sage_const_1 ] > _sage_const_0 :
        data_x.append(data[_sage_const_0 ])
for i in range(_sage_const_100 ):      
    print(i,'-th heights:')
    print(data_x[i])
    
    print(i,'-th triang:')
    print(triang[i][-_sage_const_1 ])

print('Done.')

